version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

jobs:
  run-specs-with-postgres:
    executor: postgres_ruby_3
    steps:
      - solidusio_extensions/run-tests
  run-specs-with-mysql:
    executor: solidusio_extensions/mysql
    steps:
      - solidusio_extensions/run-tests

executors:
  postgres_ruby_3:
    docker:
      - environment:
          DB: postgresql
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
        image: cimg/ruby:3.0.1-browsers
      - environment:
          POSTGRES_USER: postgres
        image: cimg/postgres:14.2

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
